In [6]:
import pandas as pd

In [7]:
#import 2015 csv
data = pd.read_csv("../Resources/2015.csv")
data.columns = data.iloc[0]
data = data[1:]
data.head()

C:\Users\Kaiza\AppData\Local\Temp\ipykernel_13320\2390086908.py:2: DtypeWarning: Columns (5,108,121,196,197,198) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../Resources/2015.csv")

,Country,Age,Gender,Tabs or Spaces,Years IT / Programming Experience,Occupation,Desktop Operating System,Desktop Operating System: write-in,Current Lang & Tech: Android,Current Lang & Tech: Arduino,...,Why use Stack Overflow: I don't use Stack Overflow,How often are Stack Overflow's answers helpful,Why answer: Help a programmer in need,Why answer: Help future programmers,Why answer: Demonstrate expertise,Why answer: Self promotion,Why answer: Sense of responsibility to developers,Why answer: No idea,Why answer: I don't answer and I don't want to,Why answer: I don't answer but I want to
1,Croatia,25-29,Male,Tabs,2 - 5 years,Back-end web developer,Ubuntu,NaN,NaN,NaN,...,NaN,Usually,NaN,NaN,It feels good to demonstrate my expertise.,Demonstrating my expertise will benefit me,I feel a sense of responsibility to the develo...,NaN,NaN,NaN
2,France,20-24,Male,Spaces,1 - 2 years,Back-end web developer,Windows 7,NaN,NaN,NaN,...,NaN,Usually,NaN,My answer will help lots of people who have th...,It feels good to demonstrate my expertise.,NaN,NaN,NaN,NaN,NaN
3,India,20-24,Male,Tabs,1 - 2 years,Back-end web developer,Windows 7,NaN,NaN,NaN,...,NaN,Rarely,NaN,NaN,NaN,Demonstrating my expertise will benefit me,NaN,NaN,NaN,NaN
4,Latvia,25-29,Male,It depends,6 - 10 years,Back-end web developer,Ubuntu,NaN,NaN,NaN,...,NaN,Usually,It feels good to help a programmer in need,My answer will help lots of people who have th...,It feels good to demonstrate my expertise.,Demonstrating my expertise will benefit me,I feel a sense of responsibility to the develo...,NaN,NaN,NaN
5,Norway,30-34,Male,Tabs,2 - 5 years,Back-end web developer,Windows 8,NaN,NaN,NaN,...,NaN,Usually,It feels good to help a programmer in need,NaN,NaN,Demonstrating my expertise will benefit me,NaN,NaN,NaN,"I don't answer much (or at all), but I want to..."

In [11]:
data.columns

Index(['Country', 'Age', 'Gender', 'Tabs or Spaces',
       'Years IT / Programming Experience', 'Occupation',
       'Desktop Operating System', 'Desktop Operating System: write-in',
       'Current Lang & Tech: Android', 'Current Lang & Tech: Arduino',
       ...
       'Why use Stack Overflow: I don't use Stack Overflow',
       'How often are Stack Overflow's answers helpful',
       'Why answer: Help a programmer in need',
       'Why answer: Help future programmers',
       'Why answer: Demonstrate expertise', 'Why answer: Self promotion',
       'Why answer: Sense of responsibility to developers',
       'Why answer: No idea', 'Why answer: I don't answer and I don't want to',
       'Why answer: I don't answer but I want to'],
      dtype='object', name=0, length=222)

In [12]:
# make df with only the important columns
cleaned = data[['Years IT / Programming Experience','Occupation','Compensation']]
cleaned['Year'] = '2015'
cleaned = cleaned.dropna()

C:\Users\Kaiza\AppData\Local\Temp\ipykernel_13320\3802260907.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned['Year'] = '2015'

In [13]:
cleaned['Occupation'].value_counts()

Full-stack web developer                                 6027
Student                                                  2357
Back-end web developer                                   1840
Desktop developer                                        1514
Front-end web developer                                  1041
Mobile developer - Android                                727
Mobile developer - iOS                                    550
Enterprise level services developer                       542
Embedded application developer                            531
Developer with a statistics or mathematics background     398
Data scientist                                            357
Executive (VP of Eng., CTO, CIO, etc.)                    344
Mobile developer                                          333
System administrator                                      299
DevOps                                                    291
Business intelligence or data warehousing expert          161
Quality Assurance                                         146
Product manager                                           136
Graphics programmer                                       136
Designer                                                  120
Machine learning developer                                115
Database administrator                                     97
Growth hacker                                              50
Mobile developer - Windows Phone                           40
Name: Occupation, dtype: int64

In [14]:
# create smaller df with only the jobs we want
analyst = cleaned[cleaned['Occupation'].str.contains('analyst')]
scientist = cleaned[cleaned['Occupation'].str.contains('scientist')]
machine = cleaned[cleaned['Occupation'].str.contains('machine')]
# engineer = cleaned[cleaned['DevType'].str.contains('engineer')]

In [15]:
# convert job titles to specific
analyst['Occupation'] = 'Data Analyst'
scientist['Occupation'] = 'Data Scientist'
machine['Occupation'] = 'Machine Learning Engineer'

C:\Users\Kaiza\AppData\Local\Temp\ipykernel_13320\3345237813.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scientist['Occupation'] = 'Data Scientist'

In [16]:
combined = pd.concat([analyst, scientist, machine], ignore_index=True)
combined

,Years IT / Programming Experience,Occupation,Compensation,Year
0,6 - 10 years,Data Scientist,"$20,000 - $40,000",2015
1,6 - 10 years,Data Scientist,"$60,000 - $80,000",2015
2,6 - 10 years,Data Scientist,"$40,000 - $60,000",2015
3,2 - 5 years,Data Scientist,Rather not say,2015
4,11+ years,Data Scientist,"$80,000 - $100,000",2015
...,...,...,...,...
352,1 - 2 years,Data Scientist,"$20,000 - $40,000",2015
353,Less than 1 year,Data Scientist,Unemployed,2015
354,11+ years,Data Scientist,"$20,000 - $40,000",2015
355,2 - 5 years,Data Scientist,"$20,000 - $40,000",2015
356,2 - 5 years,Data Scientist,"$20,000 - $40,000",2015

In [21]:
combined.to_csv('../Outputs/2016.csv', index=False)